name: Django CI

on:
  pull_request:
    branches:
      - master
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'ready for QA' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  labelChanger:
      dependencies: 
        - build
      - name: remove labels
          uses: actions-ecosystem/action-remove-labels@v1
          if: env.BASE_BRANCH == 'master'
          with:
            github_token: ${{ github.token }}
            labels: ready for QA
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: env.BASE_BRANCH == 'master'
        with:
          github_token: ${{ github.token }}
          labels: In QA
      