name: Django CI

on:
  pull_request:
    branches:
      - master
    types: [ labeled ]

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  build:
    if: ${{ github.event.label.name == 'ready for QA' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  labelChanger:
    dependencies: 
      - build
    runs-on: ubuntu-latest
    steps:
      - name: remove labels
          uses: actions-ecosystem/action-remove-labels@v1
          if: env.BASE_BRANCH == 'master'
          with:
            github_token: ${{ github.token }}
            labels: ready for QA
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: env.BASE_BRANCH == 'master'
        with:
          github_token: ${{ github.token }}
          labels: In QA

  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ github.token }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: 'In QA'
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
      